### ISSUE TITLE
ImportError: cannot import name 'UNet_ENN' from 'monai.networks.nets' 

### ISSUE THREAD

**Issue by beihaiyou** [iWeisskohl/Evidential-neural-network-for-lymphoma-segmentation#1]
I have installed monai==0.3.0, but it reports this error, could you please give me some help

**Comment by iWeisskohl** [comment]
Hello, you should copying the the file where UNet_ENN is defined  from ./models  into ./monai/networks/net.

**Comment by beihaiyou** [comment]
Thank you so much, it works!

**Comment by beihaiyou** [comment]
I use my own datas, I preprocess the datas following the paper, but the network dosen't converge. I don't know in which step I make mistakes, could you please give me some instruction? @iWeisskohl 
following is my loss graph
![image](https://user-images.githubusercontent.com/93357283/222025835-d0f406a2-b360-4445-9461-9be682dec1f1.png)
following is my data
![image](https://user-images.githubusercontent.com/93357283/222025897-82e20d5e-9da5-426b-b765-cc1c965ce05d.png)
![image](https://user-images.githubusercontent.com/93357283/222025913-0aa2165a-9ca8-4b55-a561-f4cfa6155233.png)

**Comment by iWeisskohl** [comment]
> I use my own datas, I preprocess the datas following the paper, but the network dosen't converge. I don't know in which step I make mistakes, could you please give me some instruction? @iWeisskohl following is my loss graph ![image](https://user-images.githubusercontent.com/93357283/222025835-d0f406a2-b360-4445-9461-9be682dec1f1.png) following is my data ![image](https://user-images.githubusercontent.com/93357283/222025897-82e20d5e-9da5-426b-b765-cc1c965ce05d.png) ![image](https://user-images.githubusercontent.com/93357283/222025913-0aa2165a-9ca8-4b55-a561-f4cfa6155233.png)

**Comment by iWeisskohl** [comment]
Can you give me more details how do you use the model? For example, the dataset size, the learning rate, the batch_size. Be careful of  the initialization of prototypes when you use UNet_ENN, because it is derived from the input data and the optimization of prototypes also related to your input data.

**Comment by iWeisskohl** [comment]
I suggest you to finetune the whole framework on your own dataset.
